name: Build & publish packs

on:
  push:
    tags:        
      - '*'

jobs:
  build_pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci
        
      - name: Build datapack
        run: |
          npm run build
          npm run patch-changes
          (cd .sandstone/output/datapack/extremely-important-datapack && zip -r ../extremely-important-datapack.zip .)

      - name: Build resource pack
        run: npm run res-build
      
      - name: Release packs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .resources/output/extremely-important-resources.zip
            .sandstone/output/datapack/extremely-important-datapack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
