name: Build & publish packs

on:
  push:
    tags:        
      - '*'

jobs:
  build_pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        
      - name: Build datapack
        run: |
          npm run build
          zip -r .sandstone/output/datapack/extremely-important-datapack.zip .sandstone/output/datapack/extremely-important-datapack

      - name: Build resource pack
        run: npm run res-build
      
      - name: Release packs
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .resources/output/extremely-important-resources.zip
            .sandstone/output/datapack/extremely-important-datapack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
